// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	message "github.com/dmalykh/axeloy/axeloy/message"
	mock "github.com/stretchr/testify/mock"

	model "github.com/dmalykh/axeloy/axeloy/router/model"
)

// RouteRepository is an autogenerated mock type for the RouteRepository type
type RouteRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, route
func (_m *RouteRepository) CreateRoute(ctx context.Context, route *model.Route) error {
	ret := _m.Called(ctx, route)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Route) error); ok {
		r0 = rf(ctx, route)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBySource provides a mock function with given fields: ctx, source
func (_m *RouteRepository) GetBySource(ctx context.Context, source message.Payload) ([]*model.Route, error) {
	ret := _m.Called(ctx, source)

	var r0 []*model.Route
	if rf, ok := ret.Get(0).(func(context.Context, message.Payload) []*model.Route); ok {
		r0 = rf(ctx, source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Route)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, message.Payload) error); ok {
		r1 = rf(ctx, source)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
