database:
  driver: "pgx"
  dsn: "postgre://name@pass:serv"
ways:
  drivers:
    smsru:
      path: "ways/smsru/smsru.so"
      config:
        host: ""
        username: ""
        password: ""
    graphql:
      path: "ways/graphql/graphql.so"
      config:
        addr: ":3040"