// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	message "github.com/dmalykh/axeloy/axeloy/message"
	mock "github.com/stretchr/testify/mock"

	model "github.com/dmalykh/axeloy/axeloy/way/model"

	profile "github.com/dmalykh/axeloy/axeloy/profile"

	uuid "github.com/google/uuid"
)

// Listener is an autogenerated mock type for the Listener type
type Listener struct {
	mock.Mock
}

// GetId provides a mock function with given fields:
func (_m *Listener) GetId() uuid.UUID {
	ret := _m.Called()

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// Listen provides a mock function with given fields: _a0, _a1
func (_m *Listener) Listen(_a0 context.Context, _a1 func(context.Context, message.Message) error) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, message.Message) error) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetParams provides a mock function with given fields: params
func (_m *Listener) SetParams(params model.Params) {
	_m.Called(params)
}

// Stop provides a mock function with given fields:
func (_m *Listener) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateProfile provides a mock function with given fields: ctx, _a1
func (_m *Listener) ValidateProfile(ctx context.Context, _a1 profile.Profile) (map[string]string, error) {
	ret := _m.Called(ctx, _a1)

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(context.Context, profile.Profile) map[string]string); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, profile.Profile) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
