// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	message "github.com/dmalykh/axeloy/axeloy/message"
	mock "github.com/stretchr/testify/mock"

	model "github.com/dmalykh/axeloy/axeloy/way/model"

	profile "github.com/dmalykh/axeloy/axeloy/profile"

	uuid "github.com/google/uuid"
)

// Sender is an autogenerated mock type for the Sender type
type Sender struct {
	mock.Mock
}

// GetId provides a mock function with given fields:
func (_m *Sender) GetId() uuid.UUID {
	ret := _m.Called()

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// Send provides a mock function with given fields: ctx, _a1, _a2
func (_m *Sender) Send(ctx context.Context, _a1 profile.Profile, _a2 message.Message) ([]string, error) {
	ret := _m.Called(ctx, _a1, _a2)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, profile.Profile, message.Message) []string); ok {
		r0 = rf(ctx, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, profile.Profile, message.Message) error); ok {
		r1 = rf(ctx, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetParams provides a mock function with given fields: params
func (_m *Sender) SetParams(params model.Params) {
	_m.Called(params)
}

// Stop provides a mock function with given fields:
func (_m *Sender) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateProfile provides a mock function with given fields: ctx, _a1
func (_m *Sender) ValidateProfile(ctx context.Context, _a1 profile.Profile) (map[string]string, error) {
	ret := _m.Called(ctx, _a1)

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(context.Context, profile.Profile) map[string]string); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, profile.Profile) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
