// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dmalykh/axeloy/axeloy/way/model"
	mock "github.com/stretchr/testify/mock"

	profile "github.com/dmalykh/axeloy/axeloy/profile"

	uuid "github.com/google/uuid"
)

// Way is an autogenerated mock type for the Way type
type Way struct {
	mock.Mock
}

// GetId provides a mock function with given fields:
func (_m *Way) GetId() uuid.UUID {
	ret := _m.Called()

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// SetParams provides a mock function with given fields: params
func (_m *Way) SetParams(params model.Params) {
	_m.Called(params)
}

// ValidateProfile provides a mock function with given fields: ctx, _a1
func (_m *Way) ValidateProfile(ctx context.Context, _a1 profile.Profile) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, profile.Profile) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
