// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	message "github.com/dmalykh/axeloy/axeloy/message"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"

	way "github.com/dmalykh/axeloy/axeloy/way"
)

// Wayer is an autogenerated mock type for the Wayer type
type Wayer struct {
	mock.Mock
}

// GetAvailableListeners provides a mock function with given fields: ctx
func (_m *Wayer) GetAvailableListeners(ctx context.Context) ([]way.Listener, error) {
	ret := _m.Called(ctx)

	var r0 []way.Listener
	if rf, ok := ret.Get(0).(func(context.Context) []way.Listener); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]way.Listener)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSenderById provides a mock function with given fields: ctx, id
func (_m *Wayer) GetSenderById(ctx context.Context, id uuid.UUID) (way.Sender, error) {
	ret := _m.Called(ctx, id)

	var r0 way.Sender
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) way.Sender); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(way.Sender)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSenderByName provides a mock function with given fields: ctx, name
func (_m *Wayer) GetSenderByName(ctx context.Context, name string) (way.Sender, error) {
	ret := _m.Called(ctx, name)

	var r0 way.Sender
	if rf, ok := ret.Get(0).(func(context.Context, string) way.Sender); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(way.Sender)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RunListener provides a mock function with given fields: ctx, listener, handler
func (_m *Wayer) RunListener(ctx context.Context, listener way.Listener, handler func(context.Context, message.Message) error) error {
	ret := _m.Called(ctx, listener, handler)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, way.Listener, func(context.Context, message.Message) error) error); ok {
		r0 = rf(ctx, listener, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RunListeners provides a mock function with given fields: ctx, handler
func (_m *Wayer) RunListeners(ctx context.Context, handler func(context.Context, message.Message) error) error {
	ret := _m.Called(ctx, handler)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, message.Message) error) error); ok {
		r0 = rf(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *Wayer) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StopListener provides a mock function with given fields: ctx, listener
func (_m *Wayer) StopListener(ctx context.Context, listener way.Listener) error {
	ret := _m.Called(ctx, listener)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, way.Listener) error); ok {
		r0 = rf(ctx, listener)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
