// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// Identitable is an autogenerated mock type for the Identitable type
type Identitable struct {
	mock.Mock
}

// GetId provides a mock function with given fields:
func (_m *Identitable) GetId() uuid.UUID {
	ret := _m.Called()

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}
