// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	profile "github.com/dmalykh/axeloy/axeloy/profile"
	mock "github.com/stretchr/testify/mock"
)

// Destination is an autogenerated mock type for the Destination type
type Destination struct {
	mock.Mock
}

// GetConsumer provides a mock function with given fields:
func (_m *Destination) GetConsumer() profile.Fields {
	ret := _m.Called()

	var r0 profile.Fields
	if rf, ok := ret.Get(0).(func() profile.Fields); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(profile.Fields)
		}
	}

	return r0
}

// GetWay provides a mock function with given fields:
func (_m *Destination) GetWay() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
