// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DriverConfig is an autogenerated mock type for the DriverConfig type
type DriverConfig struct {
	mock.Mock
}
