// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	driver "github.com/dmalykh/axeloy/axeloy/way/driver"
	mock "github.com/stretchr/testify/mock"

	payload "github.com/dmalykh/axeloy/axeloy/message/payload"

	profile "github.com/dmalykh/axeloy/axeloy/profile"
)

// Message is an autogenerated mock type for the Message type
type Message struct {
	mock.Mock
}

// GetDestinations provides a mock function with given fields:
func (_m *Message) GetDestinations() []driver.Destination {
	ret := _m.Called()

	var r0 []driver.Destination
	if rf, ok := ret.Get(0).(func() []driver.Destination); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]driver.Destination)
		}
	}

	return r0
}

// GetPayload provides a mock function with given fields:
func (_m *Message) GetPayload() payload.Payload {
	ret := _m.Called()

	var r0 payload.Payload
	if rf, ok := ret.Get(0).(func() payload.Payload); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(payload.Payload)
		}
	}

	return r0
}

// GetPublisher provides a mock function with given fields:
func (_m *Message) GetPublisher() profile.Fields {
	ret := _m.Called()

	var r0 profile.Fields
	if rf, ok := ret.Get(0).(func() profile.Fields); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(profile.Fields)
		}
	}

	return r0
}
