// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	message "github.com/dmalykh/axeloy/axeloy/message"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Message is an autogenerated mock type for the Message type
type Message struct {
	mock.Mock
}

// GetDestinations provides a mock function with given fields:
func (_m *Message) GetDestinations() []message.Payload {
	ret := _m.Called()

	var r0 []message.Payload
	if rf, ok := ret.Get(0).(func() []message.Payload); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]message.Payload)
		}
	}

	return r0
}

// GetSource provides a mock function with given fields:
func (_m *Message) GetSource() message.Payload {
	ret := _m.Called()

	var r0 message.Payload
	if rf, ok := ret.Get(0).(func() message.Payload); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(message.Payload)
		}
	}

	return r0
}

// GetUUID provides a mock function with given fields:
func (_m *Message) GetUUID() uuid.UUID {
	ret := _m.Called()

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}
