// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	message "github.com/dmalykh/axeloy/axeloy/message"
	mock "github.com/stretchr/testify/mock"
)

// Messager is an autogenerated mock type for the Messager type
type Messager struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, m
func (_m *Messager) Save(ctx context.Context, m message.Message) error {
	ret := _m.Called(ctx, m)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, message.Message) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveState provides a mock function with given fields: ctx, m, state, info
func (_m *Messager) SaveState(ctx context.Context, m message.Message, state message.State, info ...string) error {
	_va := make([]interface{}, len(info))
	for _i := range info {
		_va[_i] = info[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, m, state)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, message.Message, message.State, ...string) error); ok {
		r0 = rf(ctx, m, state, info...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
